import { describe, expect, it } from 'vitest';
import { validateManifest } from '../skills/telegram-port/core/manifest.js';
import { CORE_MESSAGES } from '../skills/telegram-port/core/messages.core.js';
import { manifestModule, messagesModule, parseMessages, textKeys } from '../skills/telegram-port/tools/lib/gen.mjs';
import { sampleManifest } from './fixtures.js';

const m = () => JSON.parse(JSON.stringify(sampleManifest));

describe('manifestModule', () => {
  it('writes the manifest as a const module that round-trips', () => {
    const src = manifestModule(m());
    expect(src.startsWith('// Generated by telegram-port')).toBe(true);
    expect(src.trimEnd().endsWith('} as const;')).toBe(true);
    const body = src.slice(src.indexOf('{'), src.lastIndexOf('} as const') + 1);
    expect(JSON.parse(body)).toEqual(m());
  });
});

describe('messages', () => {
  it('collects exactly the keys the engine checks for', () => {
    const texts = parseMessages(messagesModule(m()));
    expect(texts).not.toBeNull();
    expect(() => validateManifest(m(), { ...CORE_MESSAGES.ko, ...texts })).not.toThrow();
    expect(Object.keys(texts!)).toEqual(textKeys(m()));
    expect(texts!['jobs.title']).toBe('jobs.title');
  });

  it('keeps texts that already exist', () => {
    const texts = parseMessages(messagesModule(m(), { 'jobs.title': '작업' }));
    expect(texts!['jobs.title']).toBe('작업');
  });

  it('reads nothing from a file that is no longer JSON-shaped', () => {
    expect(parseMessages("export const messages = { 'a': 'b', };")).toBeNull();
    expect(parseMessages('export const x = 1;')).toBeNull();
  });
});
