// Generated by telegram-port from telegram.manifest.json. Do not edit:
// change the JSON, then run `node <skill>/tools/port.mjs gen`.
export const manifest = {
  "version": 1,
  "manifestRev": 1,
  "language": "ko",
  "owner": {
    "env": "TELEGRAM_CHAT_ID"
  },
  "menus": [
    {
      "id": "main",
      "title": "main.title",
      "items": [
        {
          "action": "status.show"
        },
        {
          "menu": "calls"
        },
        {
          "menu": "wallets"
        },
        {
          "menu": "settings"
        },
        {
          "menu": "status"
        }
      ]
    },
    {
      "id": "calls",
      "title": "calls.title",
      "items": [
        {
          "action": "calls.list"
        },
        {
          "action": "calls.mode",
          "args": [
            "off",
            "record",
            "quick"
          ]
        }
      ]
    },
    {
      "id": "wallets",
      "title": "wallets.title",
      "items": [
        {
          "action": "wallets.list"
        },
        {
          "action": "wallets.watch"
        },
        {
          "action": "wallets.unwatch"
        }
      ]
    }
  ],
  "actions": [
    {
      "id": "status.show",
      "label": "status.btn",
      "risk": "read",
      "command": "now"
    },
    {
      "id": "calls.list",
      "label": "calls.list",
      "risk": "read",
      "command": "calls"
    },
    {
      "id": "calls.mode",
      "label": "calls.mode",
      "risk": "write",
      "arg": {
        "kind": "enum"
      }
    },
    {
      "id": "wallets.list",
      "label": "wallets.list",
      "risk": "read",
      "command": "wallets"
    },
    {
      "id": "wallets.watch",
      "label": "wallets.watch",
      "risk": "write",
      "command": "watch",
      "arg": {
        "kind": "text",
        "prompt": "wallets.watch.ask"
      }
    },
    {
      "id": "wallets.unwatch",
      "label": "wallets.unwatch",
      "risk": "danger",
      "command": "unwatch",
      "arg": {
        "kind": "text",
        "prompt": "wallets.unwatch.ask"
      },
      "confirmPhrase": "REMOVE"
    }
  ],
  "settings": {
    "categories": [
      {
        "id": "calls",
        "title": "settings.calls"
      },
      {
        "id": "budget",
        "title": "settings.budget"
      },
      {
        "id": "scoring",
        "title": "settings.scoring"
      }
    ],
    "fields": [
      {
        "id": "radar.hit",
        "path": "radar.sampleRate.hit",
        "category": "calls",
        "label": "set.radarHit",
        "kind": "float",
        "ratio": true,
        "min": 0,
        "max": 1,
        "apply": "live"
      },
      {
        "id": "radar.miss",
        "path": "radar.sampleRate.miss",
        "category": "calls",
        "label": "set.radarMiss",
        "kind": "float",
        "ratio": true,
        "min": 0,
        "max": 1,
        "apply": "live"
      },
      {
        "id": "forensics.enabled",
        "path": "calls.forensics.enabled",
        "category": "calls",
        "label": "set.forensics",
        "kind": "boolean",
        "apply": "live"
      },
      {
        "id": "helius.daily",
        "path": "helius.dailyCredits",
        "category": "budget",
        "label": "set.daily",
        "kind": "int",
        "min": 0,
        "max": 1000000,
        "apply": "restart"
      },
      {
        "id": "helius.share",
        "path": "helius.forensicShare",
        "category": "budget",
        "label": "set.share",
        "kind": "float",
        "ratio": true,
        "min": 0,
        "max": 0.5,
        "apply": "restart"
      },
      {
        "id": "scoring.threshold",
        "path": "scoring.threshold",
        "category": "scoring",
        "label": "set.threshold",
        "kind": "float",
        "min": 0,
        "max": 100,
        "apply": "live"
      }
    ],
    "excluded": [
      "apiKeys.*"
    ]
  },
  "alerts": [
    {
      "id": "call.verdict",
      "template": "alert.callVerdict",
      "mutable": true
    },
    {
      "id": "wallet.move",
      "template": "alert.walletMove",
      "mutable": true
    },
    {
      "id": "budget.exhausted",
      "template": "alert.budgetExhausted",
      "mutable": false
    }
  ],
  "status": {
    "fields": [
      "calls.today",
      "wallets.tracked",
      "budget.used"
    ]
  }
} as const;
