/** The manifest as a TS module: `typeof manifest` then carries the literal ids the binding types need. */
export function manifestModule(manifest) {
  return [
    '// Generated by telegram-port from telegram.manifest.json. Do not edit:',
    '// change the JSON, then run `node <skill>/tools/port.mjs gen`.',
    `export const manifest = ${JSON.stringify(manifest, null, 2)} as const;`,
    '',
  ].join('\n');
}

/** Every text key a manifest uses, in manifest order. Must match the engine's validateManifest. */
export function textKeys(m) {
  const keys = [
    ...m.menus.map((x) => x.title),
    ...m.actions.flatMap((a) => [a.label, ...(a.arg?.prompt ? [a.arg.prompt] : [])]),
    ...(m.settings?.categories ?? []).map((c) => c.title),
    ...(m.settings?.fields ?? []).map((f) => f.label),
    ...(m.alerts ?? []).map((a) => a.template),
    ...(m.status ? [...(m.status.title ? [m.status.title] : []), ...m.status.fields.map((f) => `status.${f}`)] : []),
  ];
  return [...new Set(keys)];
}

/** A first messages file. A key shows itself until someone writes its text, so nothing is ever blank. */
export function messagesModule(m, existing = {}) {
  const texts = Object.fromEntries(textKeys(m).map((k) => [k, existing[k] ?? k]));
  return [
    "import type { Messages } from './core/index.js';",
    '',
    '// Keep this object JSON-shaped (double quotes, no trailing commas): the preview tool reads it.',
    `export const messages: Messages = ${JSON.stringify(texts, null, 2)};`,
    '',
  ].join('\n');
}

/** Reads a messages module back; null once a person has made it something JSON cannot parse. */
export function parseMessages(source) {
  const match = /=\s*(\{[\s\S]*\})\s*;?\s*$/.exec(source.trim());
  if (!match) return null;
  try {
    return JSON.parse(match[1]);
  } catch {
    return null;
  }
}
